### ISSUE TITLE
Inconsistent data loading png when `ImageIO` is installed or not

### ISSUE THREAD

**Issue by t-bltg** [JuliaIO/ImageIO.jl#41] opened 2021-12-24 21:26 UTC
With the official julia binaries, and no packages installed.

Consider:

**bug.jl**
```julia
using LinearAlgebra
using ColorTypes
using FileIO
using Pkg

test() = begin
  toucan = load("toucan.png")
  r, g, b, a = red.(toucan), green.(toucan), blue.(toucan), alpha.(toucan)
  @show norm(r) norm(g) norm(b) norm(a)
end

imageio_installed() = begin
  io = PipeBuffer()
  Pkg.status("ImageIO"; io=io)
  !occursin("No Matches in", join(readlines(io), '\n'))
end

main() = begin
  if imageio_installed()
    println("vvvv PNGFiles vvvv")
  else
    println("vvvv ImageMagick vvvv")
  end
  test()
end

main()
```

Run the following in the shell:
```bash
$ wget https://raw.githubusercontent.com/JuliaImages/TestImages.jl/images/images/toucan.png
$ julia -e 'versioninfo()'
```
<details>
  <summary>details</summary>

```julia
Julia Version 1.6.5
Commit 9058264a69 (2021-12-19 12:30 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, sandybridge)
```
</details>

```bash
$ julia -e 'using Pkg; Pkg.add(split("ColorTypes FileIO ImageMagick"))'
```
<details>
  <summary>details</summary>

```julia
    Updating registry at `~/.julia/registries/General`
   Resolving package versions...
    Updating `~/.julia/environments/v1.6/Project.toml`
  [3da002f7] + ColorTypes v0.11.0
  [5789e2e9] + FileIO v1.11.2
  [6218d12a] + ImageMagick v1.2.2
    Updating `~/.julia/environments/v1.6/Manifest.toml`
  [621f4979] + AbstractFFTs v1.0.1
  [79e6a3ab] + Adapt v3.3.1
  [d360d2e6] + ChainRulesCore v1.11.2
  [9e997f8a] + ChangesOfVariables v0.1.2
  [3da002f7] + ColorTypes v0.11.0
  [c3611d14] + ColorVectorSpace v0.9.8
  [5ae59095] + Colors v0.12.8
  [34da2185] + Compat v3.41.0
  [ffbed154] + DocStringExtensions v0.8.6
  [5789e2e9] + FileIO v1.11.2
  [53c48c17] + FixedPointNumbers v0.8.4
  [a2bd30eb] + Graphics v1.1.1
  [a09fc81d] + ImageCore v0.9.3
  [6218d12a] + ImageMagick v1.2.2
  [3587e190] + InverseFunctions v0.1.2
  [92d709cd] + IrrationalConstants v0.1.1
  [692b3bcd] + JLLWrappers v1.3.0
  [2ab3a3ac] + LogExpFunctions v0.3.6
  [dbb5928d] + MappedArrays v0.4.1
  [e94cdb99] + MosaicViews v0.3.3
  [77ba4419] + NaNMath v0.3.6
  [6fe1bfb0] + OffsetArrays v1.10.8
  [5432bcbf] + PaddedViews v0.5.10
  [21216c6a] + Preferences v1.2.3
  [189a3867] + Reexport v1.2.2
  [ae029012] + Requires v1.2.0
  [276daf66] + SpecialFunctions v2.0.0
  [cae243ae] + StackViews v0.1.1
  [62fd8b95] + TensorCore v0.1.1
  [c73af94c] + ImageMagick_jll v6.9.10-12+3
  [aacddb02] + JpegTurbo_jll v2.1.0+0
  [89763e89] + Libtiff_jll v4.3.0+0
  [efe28fd5] + OpenSpecFun_jll v0.5.5+0
  [3161d3a3] + Zstd_jll v1.5.0+0
  [b53b4c65] + libpng_jll v1.6.38+0
  [0dad84c5] + ArgTools
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8bb1440f] + DelimitedFiles
  [8ba89e20] + Distributed
  [f43a241f] + Downloads
  [b77e0a4c] + InteractiveUtils
  [b27032c2] + LibCURL
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [ca575930] + NetworkOptions
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [1a1011a3] + SharedArrays
  [6462fe0b] + Sockets
  [2f01184e] + SparseArrays
  [10745b16] + Statistics
  [fa267f1f] + TOML
  [a4e569a6] + Tar
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  [e66e0078] + CompilerSupportLibraries_jll
  [deac9b47] + LibCURL_jll
  [29816b5a] + LibSSH2_jll
  [c8ffd9c3] + MbedTLS_jll
  [14a3606d] + MozillaCACerts_jll
  [05823500] + OpenLibm_jll
  [83775a58] + Zlib_jll
  [8e850ede] + nghttp2_jll
  [3f19e933] + p7zip_jll
```
</details>

```bash
$ julia -e 'using Pkg; Pkg.add("ImageIO")' && julia bug.jl
```
<details>
  <summary>details</summary>

```julia
   Resolving package versions...
    Updating `~/.julia/environments/v1.6/Project.toml`
  [82e4d734] + ImageIO v0.5.9
    Updating `~/.julia/environments/v1.6/Manifest.toml`
  [fa961155] + CEnum v0.4.1
  [864edb3b] + DataStructures v0.18.11
  [82e4d734] + ImageIO v0.5.9
  [9b13fd28] + IndirectArrays v1.0.0
  [d25df0c9] + Inflate v0.1.2
  [f09324ee] + Netpbm v1.0.2
  [52e1d378] + OpenEXR v0.3.2
  [bac558e1] + OrderedCollections v1.4.1
  [f57f5aa1] + PNGFiles v0.3.12
  [eebad327] + PkgVersion v0.1.1
  [92933f4c] + ProgressMeter v1.7.1
  [731e570b] + TiffImages v0.5.2
  [905a6f67] + Imath_jll v3.1.2+0
  [18a262bb] + OpenEXR_jll v3.1.1+0
```
</details>

```julia
vvvv PNGFiles vvvv
norm(r) = 46.604637f0
norm(g) = 44.646324f0
norm(b) = 17.830795f0
norm(a) = 84.79643f0
```
```bash
$ julia -e 'using Pkg; Pkg.rm("ImageIO")' && julia bug.jl
```
```julia
vvvv ImageMagick vvvv
norm(r) = 46.67997f0
norm(g) = 44.775475f0
norm(b) = 17.043888f0
norm(a) = 84.79643f0
```

I do not know which one of `ImageMagick` or `ImageIO` produces valid data, but the two have different r, g, b channel data.

@johnnychen94, I think this is a blocker for https://github.com/JuliaImages/ImageInTerminal.jl/pull/58.

**Comment by johnnychen94** [comment] 2021-12-24 21:38
I've commented on https://github.com/JuliaImages/ImageInTerminal.jl/pull/58#discussion_r773100237 that the current ImageMagick_jll is buggy.

I'm closing this in favor of https://github.com/JuliaIO/ImageMagick.jl/issues/206

**Closed as completed by johnnychen94** 2021-12-24 21:38 UTC

**Comment by t-bltg** [comment] 2021-12-24 21:40
I'm sorry but this is a different issue than JuliaIO/ImageMagick.jl#206, please reopen.

If you inspect my details above you will see that `[c73af94c] + ImageMagick_jll v6.9.10-12+3` i.e. the claimed non-buggy version is installed.

Maybe this issue should be moved to https://github.com/JuliaIO/PNGFiles.jl since the following also reproduces:
```julia
using LinearAlgebra
using ImageMagick
using ColorTypes
using PNGFiles

test(img) = begin
  r, g, b, a = red.(img), green.(img), blue.(img), alpha.(img)
  @show norm(r) norm(g) norm(b) norm(a)
end

main() = begin
  println("vvvv PNGFiles vvvv")
  img = open("toucan.png") do io
    PNGFiles.load(io)
  end
  test(img)
  println("vvvv ImageMagick vvvv")
  img = open("toucan.png") do io
    ImageMagick.load(io)
  end
  test(img)
  return
end

main()
```

**Comment by johnnychen94** [comment] 2021-12-24 22:04
Ah okay; I didn't notice the Manifest is hidden in the "details" block. I think this is expected behavior since they're different image encoder backends, there will be some implementation differences.

The overall differences are tested in https://github.com/JuliaIO/PNGFiles.jl/blob/f9b2eb5239432c387fea2d0b490874854b664723/test/test_testimages.jl#L31-L38 and for this specific "toucan.png" file, it
is

```julia
julia> imdiff(img_imagemagick, img_imageio)
0.009538610505930765
```

In the future we will try to retire ImageMagick by adding JPEG wrapper, so if possible let's stick to the ImageIO result as a reference. Will this make sense to you?
